// require("./01-tipos-basicos");
// require("./02-arr-obj-interface");
// require("./03-funciones");
// require("./04-funciones-obj");
// require("./05-tarea-tipado");
// require("./06-desestructuracion-obj");
// require("./07-desestructuracion-arr");
// require("./08-desestructuracion-arg");
// require("./09-export-import");
// require("./10-clases");
// require("./11-genericos");
require("./12-decoradores-de-clases");